### ISSUE TITLE
Trying to create a Docker image to test a Galaxy-E integration

### ISSUE THREAD

**Issue by yvanlebras** [gibbona1/audio_labeler#2]
Dear Gibbona1,

Hope all is ok on your side. Thank you for your amazing work on audio labeler! We (from french Biodiversity e-infrastructure / Galaxy for ecology initiative) are thinking audio labeler can be an interesting tool to propose to our users. I started a Dockerfile here https://github.com/yvanlebras/audiolabeler_docker and just see that when the building is ok, the user is forwarded to shinyapps.io. Can you inform me if there is a way to use it without shinyapps.io ?

**Comment by gibbona1** [comment]
Closing, duplicate
